# fly.toml app configuration file generated for product-importer on 2025-11-25T12:28:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-importer'
primary_region = 'bom'

[http_service]
  internal_port = 8000
  [services.http_checks]
  path = "/healthz"
  interval = 10000
  timeout = 2000
  grace_period = "30s"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
